export {
  MOCK_RECENTS,
  MOCK_DASHBOARDS,
  MOCK_CHARTS,
  MOCK_QUERIES,
  MOCK_DATA_QUALITY_ALERTS,
  MOCK_ANNOUNCEMENTS,
  MOCK_CHANGELOG,
  MOCK_TEAM_ACTIVITY,
  MOCK_PINNED_DASHBOARDS,
  MOCK_RECENT_DATABASES,
  MOCK_TAGS,
  MOCK_REPORTS_SCHEDULE,
  MOCK_CERTIFICATIONS,
  MOCK_AI_SUGGESTIONS,
  MOCK_QUERY_RESULTS,
} from './mockData';

export {
  INITIAL_LAYOUT,
  DEFAULT_HOMEPAGES,
  STORAGE_KEYS,
} from './initialLayout';
